### ISSUE TITLE
Fresh ISO Build Sometimes Not Entering GUI

### ISSUE THREAD

**Issue by Luciousdev** [Mika-Project/base-iso#11]
**Checklist**
- [x] I have checked that there is no already similar issue.

**Which version did I used**
- [ ] Newest stable release
- [ ] Beta release
- [x] Dev build/git

**Describe the bug**
Sometimes when trying to launch a fresh build ISO it seems to launch the user in a "please configure your system". So far I have no clue why this is happening, could be a symlink issue or that the build timezones arent getting configured correctly.

**To Reproduce**
1. Build the ISO
2. Launch in VM
3. See the error

**Expected behavior**
Launch into the GUI with the calamares installer.

**Screenshots**
![image](https://github.com/Mika-Project/base-iso/assets/69113679/a7b7ffa3-73b9-41bc-8b19-3a4edc79eee5)

**Additional context**
*This doesn't always happen from my experience

**Comment by U-L-M-S** [comment]
![image](https://github.com/Mika-Project/base-iso/assets/96896184/caafd067-c33f-4221-aded-2cbc0a0a46c9)

I just got the same error. In the main version.
I don't see we using calamares in the future anymore and we need to start thinking about the LTS version.
starting today I'm focus on the project as I used to do.

I would suggest a meeting in the weekend and for a talk what to do, how to do and what are we going to do from now on. @Luciousdev  @nmihayl

**Comment by Luciousdev** [comment]
meeting sounds like a good idea! This weekend wont work for me but lets discuss that further on discord. 

I also think that we should rule out first that its really not an calamares issue. Personally I do not think that this is calamares, rather something else that is misconfigured. It requires some investigation.

**Comment by nmihayl** [comment]
Seconding that this is not a Calamares issue, if I boot in the installation media and write `systemctl enable --now sddm.service` in the TTY I do get the GUI as well as the Calamares installer, so I'm willing to guess it's either a missing or misconfigured systemd unit for SDDM. When that's cleared up, we should be able to get a consistent boot to GUI.

**Comment by Luciousdev** [comment]
I went back a couple releases in this branch: https://github.com/Mika-Project/base-iso/compare/58a7abc

That does fix the issue, so im thinking that something is just configured wrong. I'd suggest that I'll merge that branch with main and go from there. There aren' t that many changes from that release.

**Comment by nmihayl** [comment]
I'll test if that branch compiles correctly on my machine later today. Still would've been ideal to figure out what was causing the issue in the event it is encountered again in the future. Do make sure to include the GPL2 license, archiso refuses to work without it on my and possibly others' end.

**Comment by Luciousdev** [comment]
Yupp indeed, the gpl2 I still need to add to it.
