### ISSUE TITLE
Unable to build  .iso with mkarchiso

### ISSUE THREAD

**Issue by nmihayl** [Mika-Project/base-iso#9]
I am unable to build the .iso file using the steps specified in the README, attached is the logfile of the process. Attempted building on an Arch system with the most recent version of archiso, however the output directory which should exist according to the README is not created. Unspecified missing dependency issue on my end?

[log.txt](https://github.com/Mika-Project/base-iso/files/14033491/log.txt)

**Comment by nmihayl** [comment]
I may have been missing the extra/cdrtools package but even with it installed now, I am still unable to finish the build process with an output directory and a finished .iso

**Comment by Luciousdev** [comment]
I just looked into the log that you send. I wasn't able to find an obvious issue, I'll look at it tomorrow when I am home from work. Have to reinstall Arch on my main computer due to some changes in my main machine. I'll update this issue when I have an update,

**Comment by Luciousdev** [comment]
Hey there! I just changed a couple small things but I haven't been able to reproduce the issue so far. If you want we can go in a call on discord so I can see the issue you're having. But please try the latest commit to main first.

**Comment by nmihayl** [comment]
Latest commit with the GPL2 License seems to have fixed the issue, I am now able to build the .iso correctly

**Comment by Luciousdev** [comment]
I'm going to close this issue as completed now 👍
